"use client";
import Link from "next/link";
import { Workflow, ArrowUpRight, ArrowRight, Pause, Play, Trash2, ShieldCheck, Mail, Clock, GitBranch } from "lucide-react";
import { session, useRehearsal } from "../../store/index.ts";
import { Badge, Empty } from "../primitives/index.tsx";
import { MemoryMap } from "../memory-map/memory-map.tsx";
import { TEAM_ROUTES } from "../../domain/understanding/routing.ts";
import { perform } from "../shell/shell.tsx";
export function Workflows({ detail = false }: {
    detail?: boolean;
}) {
    const s = useRehearsal();
    const p = s.pattern;
    return <div className="content-page"><div className="page-heading"><div><span className="eyebrow">WORK THAT LEARNS</span><h1>{detail ? "Support triage" : "Your workflows"}<span className="accent-text">.</span></h1><p>{detail ? "Everything learned, every variable, every boundary." : "Useful patterns, learned from the way you already work."}</p></div>{p && <Badge tone={p.status === "active" ? "success" : "neutral"}>{p.status}</Badge>}</div>
    {!p ? <section className="panel big-empty"><Empty icon={<Workflow size={30}/>} title="Your first workflow starts with you.">Teach two support reports in the workspace. When a pattern emerges, you can inspect and activate it here.</Empty><Link className="button" href="/workspace">Start teaching<ArrowRight size={16}/></Link></section> : <>
    <div className="stats-grid"><div className="stat-card"><small>Matching observations</small><strong>{p.evidence.sampleSize}<span>examples</span></strong></div><div className="stat-card"><small>Calibrated confidence</small><strong>{Math.round(p.confidence * 100)}<span>%</span></strong></div><div className="stat-card"><small>Generalized values</small><strong>{p.variables.length}<span>variables</span></strong></div><div className="stat-card"><small>Estimated time saved</small><strong>{Math.round(Math.max(0, p.estimatedDurationSeconds - 15) / 60)}<span>min / run</span></strong></div></div>
    {!detail && <Link className="workflow-card panel" href="/workflows/support-triage"><span className="workflow-card-icon"><GitBranch size={25}/></span><div><h2>Customer support triage</h2><p>Mail → issue tracker → team chat → customer reply</p><div className="tag-row"><Badge tone="accent">Learned from your work</Badge><Badge><ShieldCheck size={11}/>Approval required</Badge></div></div><ArrowUpRight size={22}/></Link>}
    <section className="panel"><header className="panel-title"><div><Workflow size={17}/><strong>The learned workflow</strong></div><div className="button-row"><button className="button secondary small" onClick={() => perform(() => p.status === "active" ? session.pauseWorkflow() : s.phase === "pattern_discovered" ? session.activate() : session.reactivateWorkflow())}>{p.status === "active" ? <Pause size={14}/> : <Play size={14}/>}{p.status === "active" ? "Pause" : "Activate"}</button><button className="icon-button danger-text" aria-label="Forget workflow" onClick={() => {
                if (confirm("Forget this workflow and its teaching observations?"))
                    session.forget();
            }}><Trash2 size={16}/></button></div></header><MemoryMap full/></section>
    <div className="detail-columns"><section className="panel padded"><h2>Evidence, not certainty</h2><p className="muted">Two samples can support a candidate, but they cannot justify perfect confidence. The similarity score is discounted for the small sample.</p>{[["Action sequence", p.evidence.actionSequenceSimilarity, "55% weight"], ["Application set", p.evidence.applicationSetSimilarity, "20% weight"], ["Semantic intent", p.evidence.intentSimilarity, "25% weight"]].map(([label, score, weight]) => <div className="score-row" key={String(label)}><div><strong>{label}</strong><small>{weight}</small></div><div className="score-track"><span style={{ width: `${Number(score) * 100}%` }}/></div><b>{Math.round(Number(score) * 100)}%</b></div>)}<div className="info-note"><Clock size={16}/><p>{p.observedManualActionCount} observed actions · {p.estimatedDurationSeconds} estimated seconds per manual run. Savings are estimates, not measured productivity.</p></div></section><section className="panel padded"><h2>Trigger & permissions</h2><p className="trigger-description"><Mail size={18}/>{p.trigger.intent}</p><div className="permission-list">{p.permissions.map(permission => <div key={permission}><span>{permission.replaceAll("_", " ")}</span><Badge tone={permission === "create_external" || permission === "send_message" ? "warning" : "success"}>{permission === "create_external" || permission === "send_message" ? "Approval required" : "Allowed"}</Badge></div>)}</div><p className="muted">Payments are always blocked. No model or interface can grant itself approval.</p></section></div>
    <section className="panel padded"><h2>Variables & provenance</h2><p className="muted">A value that repeated in both examples is still recomputed when it was extracted, classified, routed, or generated.</p><div className="table-wrap"><table><thead><tr><th>Field</th><th>Derivation</th><th>Dependency</th><th>Why it remains a variable</th></tr></thead><tbody>{p.variables.map(v => <tr key={v.field}><td><code>{v.field}</code></td><td><Badge tone="accent">{v.source}</Badge></td><td>{v.dependsOn ?? "New report"}</td><td>{v.rationale}</td></tr>)}</tbody></table></div><h3>Authored constants</h3>{p.constants.length ? p.constants.map(c => <p key={c.field}><code>{c.field}</code>: {JSON.stringify(c.value)} · {c.rationale}</p>) : <p className="muted">No explicitly authored invariant values were observed. No constants were invented.</p>}</section>
    <section className="panel padded"><h2>Department → owner</h2><p className="muted">These explicit routing rules are provided configuration. Rehearsal learns when to apply them.</p><div className="routing-grid">{Object.values(TEAM_ROUTES).map(r => <div key={r.owner}><strong>{r.label}</strong><p>{r.owner}<ArrowRight size={13}/><code>#{r.channel}</code></p></div>)}</div></section></>}
  </div>;
}
