"use client";
import { useState } from "react";
import { Mail, ScanText, GitBranch, ShieldCheck, Send, Plus, Minus } from "lucide-react";
import { useRehearsal } from "../../store/index.ts";
export function MemoryMap({ full = false }: { full?: boolean }) {
  const s = useRehearsal(); const [zoom,setZoom] = useState(1); const [selected,setSelected] = useState<string | null>(null);
  const nodes = [{ id: "trigger", icon: Mail, label: "New report", sub: "mail · trigger" }, { id: "understand", icon: ScanText, label: "Understand", sub: "extract + classify" }, { id: "route", icon: GitBranch, label: "Route owner", sub: "department → owner" }, { id: "approval", icon: ShieldCheck, label: "Your approval", sub: "required boundary" }, { id: "execute", icon: Send, label: "Act & verify", sub: "issue · chat · reply" }];
  return <div className={`memory-map ${full ? "full" : ""}`}><div className="map-canvas" style={{ transform: `scale(${zoom})` }}><svg className="map-lines" viewBox="0 0 1000 180" preserveAspectRatio="none" aria-hidden="true"><path d="M90 80 H910"/><path className="variable-path" d="M300 80 V150 H690 V80"/></svg><div className="map-nodes">{nodes.map((n,i) => <button key={n.id} className={`map-node ${i === 3 ? "approval-node" : ""} ${selected === n.id ? "selected" : ""} ${s.pattern ? "learned" : ""}`} onClick={() => setSelected(selected === n.id ? null : n.id)}><n.icon size={18}/><strong>{n.label}</strong><small>{n.sub}</small>{s.phase === "completed" && <span className="node-check">✓</span>}</button>)}</div><div className="map-variables"><span>customer</span><span>category</span><span>department</span><span>owner</span><span>channel</span></div></div><div className="map-toolbar"><button className="icon-button" aria-label="Zoom out" onClick={() => setZoom(Math.max(.7,zoom-.1))}><Minus size={14}/></button><span>{Math.round(zoom*100)}%</span><button className="icon-button" aria-label="Zoom in" onClick={() => setZoom(Math.min(1.3,zoom+.1))}><Plus size={14}/></button></div>{selected && <div className="map-tooltip">{selected === "approval" ? "No issue creation or message sending can cross this boundary without your explicit approval." : selected === "route" ? "The owner and channel are derived from the new report’s department, even when both teaching examples had the same owner." : selected === "understand" ? "Literal report evidence supports the classification. Low confidence triggers human review." : selected === "execute" ? "Each adapter must confirm success. Retry resumes from the failed action." : "Only unread support reports can trigger an active workflow."}</div>}</div>;
}
